### ISSUE TITLE
Null value in column "expanded_url" of relation "tweet_urls_1135540987445600258" violates not-null constraint

### ISSUE THREAD

**Issue by 0xbrayo** [TheExGenesis/community-archive#179]
Fails with this error:
```Error processing Twitter archive: Error inserting tweet_urls_1135540987445600258: null value in column "expanded_url" of relation "tweet_urls_1135540987445600258" violates not-null constraint```

**Comment by DefenderOfBasic** [comment]
thank you for the report @0xbrayo ! are you able to share your archive with me so we can try and reproduce this? Maybe upload it to drive & share a link here or email `defenderofbasic@proton.me` ?

**Comment by 0xbrayo** [comment]
Uploaded to google drive. Emailed you the link.

**Comment by 0xbrayo** [comment]
@DefenderOfBasic  Any updates?

**Comment by DefenderOfBasic** [comment]
@ri72miieop is looking into it now.

**Comment by ri72miieop** [comment]
hi @0xbrayo there was an issue with the tweet 1155140493451440129 where it didn't have a field that is required from our side. I think this was some problem with the Twitter export. I removed that tweet and uploaded your archive: https://www.community-archive.org/user/1135540987445600258. Welcome. :)

**Comment by 0xbrayo** [comment]
Thanks😊

**Comment by DefenderOfBasic** [comment]
Thanks @ri72miieop !!

**Comment by DefenderOfBasic** [comment]
And thank you @0xbrayo for reporting this!!

**Comment by 0xbrayo** [comment]
@ri72miieop @DefenderOfBasic can a fix be pushed to the code, subsequent uploads from me or other people might cause the same error. Warn users that some tweets have been dropped due to malformed schema etc. Also I'm assuming we can do updates by requesting archives in the future and uploading those.

**Comment by ri72miieop** [comment]
yeah, you're right. I think this is pretty rare and I'd like to understand when it happens better, but I could also check later the db to see which tweet_urls are set to empty and this way people no longer get errors moving forward so it's a win-win.

yeah you can update it by re-uploading a more recent archive
