### ISSUE TITLE
permalinks for tweets

### ISSUE THREAD

**Issue by TheExGenesis** [TheExGenesis/community-archive#44]
people may want to upload archives from deleted accounts

https://x.com/_deepfates/status/1832128115990262244

**Comment by ri72miieop** [comment]
twitter follows the "<domain>/<it_doesn't_matter/status/<tweet_id>" pattern it would be cool if we did the same. this would make viewing it on twitter/x or on community archives easily interchangeable.

**Comment by TheExGenesis** [comment]
> twitter follows the "/<it_doesn't_matter/status/<tweet_id>" pattern it would be cool if we did the same. this would make viewing it on twitter/x or on community archives easily interchangeable.

@DefenderOfBasic wyt?

**Comment by DefenderOfBasic** [comment]
I don't feel too strongly about it, would be nice to have that consistency if it's an easy switch (not sure how to do the `<doesn't matter>` prefix). We do have permalinks now as of https://github.com/TheExGenesis/community-archive/pull/66, It's just `/tweets/<tweet_id>`.

https://www.community-archive.org/tweets/1618561012076277761

```
/tweets/<tweet_id>
```

I'm thinking _most_ use cases users wouldn't be replacing the URL by hand, but instead would be generating it/rewriting the URL with some script? (and in those cases it's trivial to go from original x.com url to the community archive, as long as you have tweet id)

**Comment by TheExGenesis** [comment]
closing this for now, as a recent pr took care of it
