### ISSUE TITLE
Show stats when not logged in?

### ISSUE THREAD

**Issue by DefenderOfBasic** [TheExGenesis/community-archive#48]
The stats only show when you're logged in:

> 19 accounts have uploaded a total of 382689 tweets. We also have 1385688 liked tweets.

would be nice to show this big on the homepage to incentivize people to join!

**Comment by TheExGenesis** [comment]
it does, there's been a bug where it doesn't show every time but I didn't get a chance to figure out the cause. Maybe the request just fails often?

**Comment by DefenderOfBasic** [comment]
hmmmm yeah, i refreshed a couple times, it does work. I do see a failed request in the console

**Comment by DefenderOfBasic** [comment]
I think at the very least the web page should communicate the status for clarity:

- say "loading" or show an icon when request is pending
- say "failed" when it failed 

(same for the tweet feed. when it fails it's not clear what happened, and I originally assumed you can only see it when logged in)

**Comment by DefenderOfBasic** [comment]
Closing since the stats do already show up when not logged in
