### ISSUE TITLE
Make "likes" optional?

### ISSUE THREAD

**Issue by zrkrlc** [TheExGenesis/community-archive#51]
Aside from `direct-messages.js`, is there anything else we can opt not to include?

I'm a coward and I don't want my likes to be seen 😅

**Comment by DefenderOfBasic** [comment]
I don't know if it's going to fail to upload right now without likes, but I think we want the app to gracefully handle it if it doesn't already! I think the minimum really should be the big tweets.json?

> The only things that leave your machine are 1. profile information
              2. tweets, 3. likes, 4. followers/following

**Comment by DefenderOfBasic** [comment]
I think that makes sense, especially now that likes are private, thanks for opening this @zrkrlc

**Comment by DefenderOfBasic** [comment]
Yeah ok right now it will throw an error if it doesn't find one of the "required files"

https://github.com/open-birdsite-db/open-birdsite-db/blob/bd538da457994a6d2870176f11aa342ac30dc6f9/src/components/UploadTwitterArchive.tsx#L206

but I think we can do some re-architecting to make that optional

**Comment by TheExGenesis** [comment]
Agreed that we could makes likes optional especially since they're private on twitter now. 

However, they're really useful to know what tweets that you interacted with were saying. If you reply to someone and like it, the text of the OP will be in your archive. If you don't like it, it won't.

**Comment by TheExGenesis** [comment]
I'd be very keen on an option to include likes only up to the point where they became private, to match ppl's prior expectations
