### ISSUE TITLE
Community stats timing out because of counting liked_tweets

### ISSUE THREAD

**Issue by TheExGenesis** [TheExGenesis/community-archive#52]
Apparently 1.4M records breaks it. Could try to increase the timeout, or find a way to calculate that stat and cache it in a table

**Comment by DefenderOfBasic** [comment]
Yeah one thing I did on a side project recently is, you can have supabase triggers that run (on specific updates/at specific times) that can do an SQL query and store the result in a separate table. 

In that project I had it run on every new row, and just +1 to a column in a different table (so it doesn't need to re-count all rows, just does the smallest update)
