### ISSUE TITLE
Upload a snapshot of the DB dump somewhere we can access

### ISSUE THREAD

**Issue by DefenderOfBasic** [TheExGenesis/community-archive#54]
We want to have downloadable snapshots automatically https://github.com/open-birdsite-db/open-birdsite-db/issues/47. In the meantime, @TheExGenesis can you upload a snapshot manually somewhere? This will help give people access to the initial dataset while we get this working, and also give us a chance to explore ways to speed up backend search/scaling etc.

**Comment by DefenderOfBasic** [comment]
Would be nice to put it on CloudFlare / S3 or whatever, but whatever works for now. Google Drive, or I think you can even upload it to github here, as a release: https://github.com/open-birdsite-db/open-birdsite-db/releases/new

**Comment by TheExGenesis** [comment]
put it in releases, would be cool to have a machine regularly uploading to releases
https://github.com/TheExGenesis/community-archive/releases/tag/dump
