### ISSUE TITLE
Add a .md page explaining our policy

### ISSUE THREAD

**Issue by TheExGenesis** [TheExGenesis/community-archive#9]
No saving emails, no saving dms, only follow graph, profile, tweets, and pictures

read only api, full dump of public tweets

in the future: filter which of your tweets are public?

more stuff?

**Comment by TheExGenesis** [comment]
like an FAQ

**Comment by DefenderOfBasic** [comment]
Done in https://github.com/TheExGenesis/community-archive/pull/68

**Comment by stevekrouse** [comment]
I found it hard to find this on the homepage. I would suggest a single line on the homepage (near where you ask for the archive) that says "We do not store your private information, such as DMs. You can optionally tell us not to store your like data as well."

**Comment by stevekrouse** [comment]
Personally, given how private my DMs are, I'd also love two extra security features:

1. Show me how to delete my DMs from my archive before I send it to you
2. Link me to the lines of code in your GitHub repo that clearly show you *not* storing my private data
